window.SITE_DATA = Object.freeze({
  company: {
    name: "深圳林益科技有限公司",
    englishName: "LINYI TECHNOLOGY",
    hotline: "13798267100",
  },
  news: [
    {
      title: "9000万辆电动车消费者，捧出一位247亿天津首富",
      text: "公司聚焦新能源、电动车及 3C 消费电子三大核心领域，重点布局工商储能、混合逆变器与智能终端产品线，持续为全球客户提供优质产品与专业服务。",
      date: "2025-07-02",
      image: "./assets/optimized/home/news-feature.jpg",
      url: "https://36kr.com/p/3360571210815879",
    },
    {
      title: '在不确定中把握确定，工商储"远景公式"发布',
      text: "新增逆变模式、整流模式、MPPT 充电与 UPS 切换信息，方便海外客户快速选型与技术比对。",
      date: "2025-06-11",
      image: "./assets/optimized/home/news-feature.jpg",
      url: "https://36kr.com/p/3331779569887494",
    },
    {
      title: "中国电动两轮车正在更快、更容易地出海",
      text: "电机、轮胎、控制器、电池与续航等关键字段已标准化，支持后续报价与详情页扩展。",
      date: "2026-03-26",
      image: "./assets/optimized/home/news-feature.jpg",
      url: "https://36kr.com/p/3739632547283203",
    },
    {
      title: "月销破亿元，投影仪在抖音卖爆了",
      text: "投影仪覆盖青春版、标准版与 PRO 版，蓝牙音箱补充尺寸、重量与主要接口功能。",
      date: "2024-03-07",
      image: "./assets/optimized/home/news-feature.jpg",
      url: "https://36kr.com/p/2679087888813572",
    },
    {
      title: '中国新能源打响"海湾战争"，传音、德业激战伊拉克',
      text: "UNISOC T107、2.4 英寸屏、基础影像与多媒体能力已统一录入，便于渠道资料输出。",
      date: "2025-07-16",
      image: "./assets/optimized/home/news-feature.jpg",
      url: "https://36kr.com/p/3379680270047625",
    },
  ],
  about: {
    summary:
      "深圳林益科技有限公司是一家集研发、生产、销售与服务于一体的工贸一体型企业，专注于新能源移动储能、光伏逆变器、二三轮电动车，以及3C消费电子领域。",
    fullText:
      "深圳林益科技有限公司是一家集研发、生产、销售与服务于一体的工贸一体型企业，专注于新能源移动储能、光伏逆变器、二三轮电动车，以及3C消费电子领域，涵盖投影仪、智能手机、高速吹风机等智能硬件产品。\n\n依托自身制造基础与产品整合能力，我们不仅为客户提供优质成品，更能提供从产品定义、研发整合、供应链协同到选型落地的全链路支持。无论是ODM定制还是品牌配套，林益科技都能快速响应，灵活交付。\n\n在研发整合方面，我们跨领域整合电力电子、电池管理、智能控制等技术，提升产品可靠性，加速从构想到量产的进程。\n\n在产品选型方面，我们结合市场趋势与不同应用场景，为客户提供精准、具备竞争力的配置建议，避免「配置过剩」或「性能不足」。\n\n在供应链方面，我们建立了稳定的元器件与材料供应体系，配合自有工厂产能与质量控制能力，在成本、交期与品质之间实现更优平衡。\n\n以工贸一体为根基，以「技术整合+供应服务」为核心，深圳林益科技致力于成为值得信赖的新能源与智能硬件合作伙伴。",
  },
  products: [
    {
      code: "01",
      name: "工商储",
      text: "面向工商业场景的模块化储能系统，支持稳定供电与灵活扩容，适用于园区、工厂和综合能源管理项目。",
      image: "./assets/optimized/products/energy-storage.jpg",
      tags: ["新能源", "储能", "工商储"],
    },
    {
      code: "02",
      name: "混合逆变器",
      text: "支持光伏与市电协同输入的智能逆变设备，兼顾能源转换效率与供电连续性，适合家庭及工商业多场景应用。",
      image: "./assets/optimized/products/hybrid-inverter.jpg",
      tags: ["新能源", "逆变器", "MPPT"],
    },
    {
      code: "03",
      name: "二轮车",
      text: "面向城市通勤与短途配送的电动二轮车，整车风格时尚、操控轻便，兼顾日常出行效率与骑行舒适度。",
      image: "./assets/optimized/products/two-wheel-scooter.jpg",
      tags: ["电动车", "二轮", "外销"],
    },
    {
      code: "04",
      name: "三轮车",
      text: "面向货运与短途运输场景的实用型电动三轮车，具备稳定承载能力与良好通过性，适合高频运输作业。",
      image: "./assets/optimized/products/tricycle.jpg",
      tags: ["电动车", "三轮", "货运"],
    },
    {
      code: "05",
      name: "助力自行车",
      text: "轻量化助力车型，适用于城市代步与休闲骑行，具备便捷操控体验和稳定续航表现。",
      image: "./assets/optimized/products/e-bike.jpg",
      tags: ["电动车", "助力", "城市通勤"],
    },
    {
      code: "06",
      name: "投影仪",
      text: "多版本智能投影产品，适用于家庭观影、卧室娱乐与轻商务展示，具备清晰画质与便捷操作体验。",
      image: "./assets/optimized/products/projector.jpg",
      tags: ["3C", "投影仪", "多版本"],
    },
    {
      code: "07",
      name: "手机",
      text: "实用型功能手机，聚焦稳定通信与基础娱乐需求，适用于日常联系、备用机及渠道分销场景。",
      image: "./assets/optimized/products/phone-photo.jpg",
      tags: ["3C", "手机", "功能机"],
    },
    {
      code: "08",
      name: "蓝牙音箱",
      text: "便携式蓝牙音箱，适合户外聚会与家庭播放，音质清晰、连接便捷，满足多场景音乐使用需求。",
      image: "./素材信息/蓝牙音箱/首页.png",
      tags: ["3C", "蓝牙音箱", "便携音频"],
    },
  ],
  contacts: [
    { label: "服务热线", value: "13798267100" },
    { label: "公司名称", value: "深圳林益科技有限公司" },
    { label: "企业邮箱", value: "liuliping@linyitec.com" },
    { label: "公司地址", value: "中国广东省深圳市光明区振兴路智慧城科创园" },
    { label: "微信", value: "13798267100" },
  ],
});
