window.SITE_DATA = Object.freeze({
  company: {
    name: "深圳林益科技有限公司",
    englishName: "LINYI TECHNOLOGY",
    hotline: "400-XXX-XXXX",
  },
  news: [
    {
      title: "9000万辆电动车消费者，捧出一位247亿天津首富",
      text: "基于公司 2026 外销产品目录，我们已完成新能源、电动车与 3C 三大方向的资料整合。当前重点覆盖工商储、混合逆变器与智能终端产品线，后续将持续发布新品与参数升级信息。",
      date: "2025-07-02",
      image: "./素材信息/资讯/Snipaste_2026-05-30_11-53-10.png",
      url: "https://36kr.com/p/3360571210815879",
    },
    {
      title: '在不确定中把握确定，工商储"远景公式"发布',
      text: "新增逆变模式、整流模式、MPPT 充电与 UPS 切换信息，方便海外客户快速选型与技术比对。",
      date: "2025-06-11",
      image: "./素材信息/资讯/Snipaste_2026-05-30_11-53-10.png",
      url: "https://36kr.com/p/3331779569887494",
    },
    {
      title: "中国电动两轮车正在更快、更容易地出海",
      text: "电机、轮胎、控制器、电池与续航等关键字段已标准化，支持后续报价与详情页扩展。",
      date: "2026-03-26",
      image: "./素材信息/资讯/Snipaste_2026-05-30_11-53-10.png",
      url: "https://36kr.com/p/3739632547283203",
    },
    {
      title: "月销破亿元，投影仪在抖音卖爆了",
      text: "投影仪覆盖青春版、标准版与 PRO 版，蓝牙音箱补充尺寸、重量与主要接口功能。",
      date: "2024-03-07",
      image: "./素材信息/资讯/Snipaste_2026-05-30_11-53-10.png",
      url: "https://36kr.com/p/2679087888813572",
    },
    {
      title: '中国新能源打响"海湾战争"，传音、德业激战伊拉克',
      text: "UNISOC T107、2.4 英寸屏、基础影像与多媒体能力已统一录入，便于渠道资料输出。",
      date: "2025-07-16",
      image: "./素材信息/资讯/Snipaste_2026-05-30_11-53-10.png",
      url: "https://36kr.com/p/3379680270047625",
    },
  ],
  about: {
    summary:
      "深圳林益科技有限公司是一家专注于外贸市场的多品类产品供应商，业务涵盖新能源、电动车及 3C 消费电子三大核心领域。公司致力于为全球客户提供优质的产品与完善的服务，持续推动技术创新与品质升级。",
  },
  products: [
    {
      code: "01",
      name: "工商储",
      text: "面向工商业场景的模块化储能系统，支持稳定供电与灵活扩容，适用于园区、工厂和综合能源管理项目。",
      image: "./素材信息/工商储/ChatGPT Image 2026年5月30日 02_07_45.png",
      tags: ["新能源", "储能", "工商储"],
    },
    {
      code: "02",
      name: "混合逆变器",
      text: "支持光伏与市电协同输入的智能逆变设备，兼顾能源转换效率与供电连续性，适合家庭及工商业多场景应用。",
      image: "./assets/material-products/hybrid-inverter.png",
      tags: ["新能源", "逆变器", "MPPT"],
    },
    {
      code: "03",
      name: "二轮车",
      text: "面向城市通勤与短途配送的电动二轮车，整车风格时尚、操控轻便，兼顾日常出行效率与骑行舒适度。",
      image: "./assets/material-products/two-wheel-scooter.png",
      tags: ["电动车", "二轮", "外销"],
    },
    {
      code: "04",
      name: "三轮车",
      text: "面向货运与短途运输场景的实用型电动三轮车，具备稳定承载能力与良好通过性，适合高频运输作业。",
      image: "./assets/material-products/tricycle.png",
      tags: ["电动车", "三轮", "货运"],
    },
    {
      code: "05",
      name: "助力自行车",
      text: "轻量化助力车型，适用于城市代步与休闲骑行，具备便捷操控体验和稳定续航表现。",
      image: "./assets/material-products/e-bike.png",
      tags: ["电动车", "助力", "城市通勤"],
    },
    {
      code: "06",
      name: "投影仪",
      text: "多版本智能投影产品，适用于家庭观影、卧室娱乐与轻商务展示，具备清晰画质与便捷操作体验。",
      image: "./assets/material-products/projector.jpg",
      tags: ["3C", "投影仪", "多版本"],
    },
    {
      code: "07",
      name: "手机",
      text: "实用型功能手机，聚焦稳定通信与基础娱乐需求，适用于日常联系、备用机及渠道分销场景。",
      image: "./assets/material-products/phone-photo.png",
      tags: ["3C", "手机", "功能机"],
    },
    {
      code: "08",
      name: "蓝牙音箱",
      text: "便携式蓝牙音箱，适合户外聚会与家庭播放，音质清晰、连接便捷，满足多场景音乐使用需求。",
      image: "./assets/material-products/bluetooth-speaker.png",
      tags: ["3C", "蓝牙音箱", "便携音频"],
    },
  ],
  contacts: [
    { label: "服务热线", value: "400-XXX-XXXX" },
    { label: "公司名称", value: "深圳林益科技有限公司" },
    { label: "企业邮箱", value: "待补充" },
    { label: "公司地址", value: "待补充" },
    { label: "微信", value: "待补充" },
    { label: "WhatsApp", value: "待补充" },
  ],
});
